[package]
name = "murgi_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
dotenv = "0.15"
tracing = "0.1.23"
tracing-subscriber = "0.2"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
features = ["framework"]
