[package]
name = "murgi_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
features = ["framework"]
