#+TITLE: Murgi Bot
#+AUTHOR: Dat Adithya
#+DESCRIPTION: A Discord Bot, made for the Murgi Clan.
#+OPTIONS: \n:t

* What is this?
A Discord Bot made for the benefit of a group of friends in a Discord Server.

The Murgi Bot is a service that listens to messages in a Discord Server, and when called using it's specified prefixes, or receives an alert that requires it to respond, it does exactly that.

There's a bunch of cool features that comes with the Murgi Bot, and here's a list of these features,
- [X] Howls upon request, and when all four murgis howl.
- [X] Queries piratebay for magnet links to games.
- [X] Can roll DnD dices, and random numbers in a specified range.
- [ ] Play songs from YouTube.
- [ ] Play anime from GogoAnime.
- [ ] Stream videos from YouTube.

* Installation
In order to set up the Murgi Bot, you will be required to install Rust, and set up a Rust Development environment, which is present in detail in the [[https://doc.rust-lang.org/stable/book/ch01-01-installation.html][Rust Book]].

The bot also utilizes the Serenity Library in order to interact with the Discord API running in the backend, however, all of the development set up will be done by a simple =cargo build= or a =cargo run=, so, there's not much to worry about there.

There is also an ongoing development of a Dockerfile, and a =docker-compose.yml= for the Murgi Bot, to be developed as a containerized application.

Finally, there is a requirement for a few environment variables in order to work with Murgi Bot, these are defined in the =.env.example= file.
