name: Murgi RPi4 Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      if: (github.ref == 'refs/heads/main' || github.event_name == 'push') && github.repository == 'dat-adi/MurgiBot'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile-RPi4 --tag datadi/murgi_bot:armv7-unknown-gnueabihf-latest

    - name: Publish Docker Image
      if: (github.ref == 'refs/heads/main' || github.event_name == 'push') && github.repository == 'dat-adi/MurgiBot'
      run: docker push datadi/murgi_bot
