name: Murgi Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Login to DockerHub
      if: (github.ref == 'refs/heads/main' || github.event_name == 'push') && github.repository == 'dat-adi/murgi_bot'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker buildx build \
          --tag datadi/murgi_bot:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 . 

    - name: Publish Docker Image
      if: (github.ref == 'refs/heads/main' || github.event_name == 'push') && github.repository == 'dat-adi/murgi_bot'
      run: docker push datadi/murgi_bot
