name: Murgi Docker CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub

      if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'dat-adi/murgi_bot'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag datadi/murgi_bot:latest

    - name: Publish Docker Image
      if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'dat-adi/murgi_bot'
      run: docker push datadi/murgi_bot
